//Given an array arr[] of N positive elements. The task is to find the Maximum AND Value generated by any pair of the element from the array.

Input: a[] = {4, 8, 12, 16}
Output: 8
  
Input: a[] = {4, 8, 16, 2}
Output: 0
  
Method 1 (Naive solution)

int findMaxium(int a[], int n)
{
    int m = 0;
    for(int i = 0; i < n; i++) 
    {
        for(int j = i + 1; j < n; j++)
            m = max(m, a[i] & a[j]); 
    }

    return m; 
}

.................................................
  
Method 2
  
// Utility function to check number of elements having set msb as of pattern

int checkBit(int pattern, int arr[], int n)
{
    int count = 0;
    for (int i = 0; i < n; i++)
        if ((pattern & arr[i]) == pattern)
            count++;
    return count;
}
 
// Function for finding maximum and value pair
int maxAND (int arr[], int n)
{
    int res = 0, count;
 
    // iterate over total of 30bits from msb to lsb
    for (int bit = 31; bit >= 0; bit--)
    {
        // find the count of element having set  msb
        count = checkBit(res | (1 << bit),arr,n);
 
        // if count >= 2 set particular bit in result
        if ( count >= 2 )        
            res |= (1 << bit);        
    }
 
    return res;
}
